# Generated by Django 2.0.1 on 2018-03-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRA', '0002_auto_20180320_1622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitor',
            table='Visitor',
        ),
    ]
