# Generated by Django 2.0.1 on 2018-03-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRA', '0003_auto_20180321_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
