# Generated by Django 2.0.1 on 2018-03-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRA', '0006_auto_20180323_1540'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitor',
            table='Visitor',
        ),
    ]
