# Generated by Django 2.0.1 on 2018-03-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRA', '0007_auto_20180323_1541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visitor',
            table='Visitors',
        ),
    ]
